<a href="https://colab.research.google.com/github/Vagarh/IUdigital/blob/main/Introduccion_a_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print('1D array: ')
print(a)

1D array: 
[1 2 3]


In [ ]:
b=np.array([(1,2,3),(4,5,6)])
print('2D array: ')
print(b)

2D array: 
[[1 2 3]
 [4 5 6]]


In [ ]:
#Numpy vs listas de python
import sys

In [ ]:
#Memoria
S=range(1000)
print('Resultado lista de python: ')
print(sys.getsizeof(5)*len(S))
print()

Resultado lista de python: 
28000



In [ ]:
D=np.arange(1000)
print('Resultado Numpy Array: ')
print(D.size*D.itemsize)
print()

Resultado Numpy Array: 
8000



In [ ]:
#Velocidad
import time
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print((time.time()-start)*1000)

291.84603691101074
52.80613899230957


In [ ]:
# Crear una matriz de unos - 3 filas 4 columnas
unos = np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Crear una matriz de ceros - 3 filas 4 columnas
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Crear una matriz con valores aleatorios
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.71537032 0.80180369]
 [0.06265592 0.55212786]]


In [ ]:
# Crear una matriz vacía
vacia = np.empty((3,2))
print(vacia)

[[4.67918271e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [ ]:
# Crear una matriz con un solo valor
full = np.full((2,2),54)
print(full)

[[54 54]
 [54 54]]


In [ ]:
# Crear una matriz con valores espaciados uniformemente
espacio1 = np.arange(0,30,5)
print(espacio1)
espacio2 = np.linspace(0,2,5)
print(espacio2)

[ 0  5 10 15 20 25]
[0.  0.5 1.  1.5 2. ]


In [ ]:
# Crear una matriz identidad
identidad1 = np.eye(4,4)
print(identidad1)
identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Conocer las dimensiones de una matriz
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [ ]:
# Conocer el tipo de los datos
a = np.array([(1,2,3)])
print(a.dtype)

int64


In [ ]:
# Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [ ]:
# Cambio de forma de una matriz
a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [ ]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [ ]:
# Extraer los valores de todas las filas ubicados en la columna 3 
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


In [ ]:
# Encontrar el mínimo, máximo y la suma
a= np.array([2,4,8])
print(a.min())
print(a.max())
print(a.sum())

2
8
14


# **PANDAS**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = np.array([['','Col1','Col2'], ['Fila1',11,22], ['Fila2',33,44]])          
print(pd.DataFrame(data = data[1:,1:], index = data[1:,0], columns = data[0,1:]))

      Col1 Col2
Fila1   11   22
Fila2   33   44


In [ ]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
print('DataFrame:')
print(df)

DataFrame:
   0  1  2
0  1  2  3
1  4  5  6


In [ ]:
series = pd.Series({"Argentina":"Buenos Aires", "Chile":"Santiago de Chile", "Colombia":"Bogotá", "Perú":"Lima"})
print('Series:')
print(series)

Series:
Argentina         Buenos Aires
Chile        Santiago de Chile
Colombia                Bogotá
Perú                      Lima
dtype: object


In [ ]:
#Forma del DataFrame
print('Forma del DataFrame:')
print(df.shape)
print()

Forma del DataFrame:
(2, 3)



In [ ]:
#Altura del DataFrame
print('Altura del DataFrame:')
print(len(df.index))

Altura del DataFrame:
2


In [ ]:
#Estadísticas del DataFrame
print('Estadísticas del DataFrame:')
print(df.describe())

Estadísticas del DataFrame:
             0        1        2
count  2.00000  2.00000  2.00000
mean   2.50000  3.50000  4.50000
std    2.12132  2.12132  2.12132
min    1.00000  2.00000  3.00000
25%    1.75000  2.75000  3.75000
50%    2.50000  3.50000  4.50000
75%    3.25000  4.25000  5.25000
max    4.00000  5.00000  6.00000


In [ ]:
#Media de las columnas DataFrame
print('Media de las columnas DataFrame:')
print(df.mean())

Media de las columnas DataFrame:
0    2.5
1    3.5
2    4.5
dtype: float64


In [ ]:
#Correlación del DataFrame
print('Correlación del DataFrame:')
print(df.corr())

Correlación del DataFrame:
     0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0


In [ ]:
#Cuenta los datos del DataFrame
print('Conteo de datos del DataFrame:')
print(df.count())

Conteo de datos del DataFrame:
0    2
1    2
2    2
dtype: int64


In [ ]:
#Desviación estándar de cada columna del DataFrame
print('Desviación estándar de la columna del DataFrame:')
print(df.std())

Desviación estándar de la columna del DataFrame:
0    2.12132
1    2.12132
2    2.12132
dtype: float64


In [ ]:
#Seleccionar la primera columna del DataFrame
print('Primera columna del DataFrame:')
print(df[0])

Primera columna del DataFrame:
0    1
1    4
Name: 0, dtype: int64


In [ ]:
#Seleccionar dos columnas del DataFrame
print('Dos columnas del DataFrame:')
print(df[[0, 1]])

Dos columnas del DataFrame:
   0  1
0  1  2
1  4  5


In [ ]:
#Seleccionar el valor de la primera fila y última columna del DataFrame
print('Valor de la primera fila y última columna del DataFrame:')
print(df.iloc[0][2])

Valor de la primera fila y última columna del DataFrame:
3


In [ ]:
#Seleccionar los valores de la primera fila del DataFrame
print('Valores de la primera fila del DataFrame:')
print(df.loc[0])

Valores de la primera fila del DataFrame:
0    1
1    2
2    3
Name: 0, dtype: int64


In [ ]:
#Seleccionar los valores de la primera fila del DataFrame
print('Valores de la primera fila del DataFrame:')
print(df.iloc[0,:])

Valores de la primera fila del DataFrame:
0    1
1    2
2    3
Name: 0, dtype: int64


**PREPROCESAMIENTO DE IMFORMACIÓN**


**Caso Titanic**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
ruta='/content/sample_data/train_Titanic.csv'

In [ ]:
df=pd.read_csv(ruta)

In [ ]:
df.head()
#df.tail()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
#Reemplazar titulos: df.columns=cabecera
titulos = ["ID", "sobreviviente", "Clase", "Nombre", "Sexo", "edad", "Hermanos", "Hijos", "Ticket", "Tarifa", "Cabina", "Embarque"]
df.columns = titulos
df.head()

ID  sobreviviente  Clase  ...   Tarifa Cabina  Embarque
0   1              0      3  ...   7.2500    NaN         S
1   2              1      1  ...  71.2833    C85         C
2   3              1      3  ...   7.9250    NaN         S
3   4              1      1  ...  53.1000   C123         S
4   5              0      3  ...   8.0500    NaN         S

[5 rows x 12 columns]

In [ ]:
ruta=r'D:\Usuarios\sebacoza\OneDrive - Seguros Suramericana, S.A\Documents\SEC\Datos_Train_Esp.csv'

In [ ]:
df.to_csv(ruta)

In [ ]:
df.dtypes

ID                 int64
sobreviviente      int64
Clase              int64
Nombre            object
Sexo              object
edad             float64
Hermanos           int64
Hijos              int64
Ticket            object
Tarifa           float64
Cabina            object
Embarque          object
dtype: object

In [ ]:
df.describe()

ID  sobreviviente  ...       Hijos      Tarifa
count  891.000000     891.000000  ...  891.000000  891.000000
mean   446.000000       0.383838  ...    0.381594   32.204208
std    257.353842       0.486592  ...    0.806057   49.693429
min      1.000000       0.000000  ...    0.000000    0.000000
25%    223.500000       0.000000  ...    0.000000    7.910400
50%    446.000000       0.000000  ...    0.000000   14.454200
75%    668.500000       1.000000  ...    0.000000   31.000000
max    891.000000       1.000000  ...    6.000000  512.329200

[8 rows x 7 columns]

In [ ]:
df.describe(include="all")

ID  sobreviviente       Clase  ...      Tarifa   Cabina  Embarque
count   891.000000     891.000000  891.000000  ...  891.000000      204       889
unique         NaN            NaN         NaN  ...         NaN      147         3
top            NaN            NaN         NaN  ...         NaN  B96 B98         S
freq           NaN            NaN         NaN  ...         NaN        4       644
mean    446.000000       0.383838    2.308642  ...   32.204208      NaN       NaN
std     257.353842       0.486592    0.836071  ...   49.693429      NaN       NaN
min       1.000000       0.000000    1.000000  ...    0.000000      NaN       NaN
25%     223.500000       0.000000    2.000000  ...    7.910400      NaN       NaN
50%     446.000000       0.000000    3.000000  ...   14.454200      NaN       NaN
75%     668.500000       1.000000    3.000000  ...   31.000000      NaN       NaN
max     891.000000       1.000000    3.000000  ...  512.329200      NaN       NaN

[11 rows x 12 columns]

In [ ]:
#30 filas superiores y 30 filas inferiores.
df.info

<bound method DataFrame.info of       ID  sobreviviente  Clase  ...   Tarifa Cabina  Embarque
0      1              0      3  ...   7.2500    NaN         S
1      2              1      1  ...  71.2833    C85         C
2      3              1      3  ...   7.9250    NaN         S
3      4              1      1  ...  53.1000   C123         S
4      5              0      3  ...   8.0500    NaN         S
..   ...            ...    ...  ...      ...    ...       ...
886  887              0      2  ...  13.0000    NaN         S
887  888              1      1  ...  30.0000    B42         S
888  889              0      3  ...  23.4500    NaN         S
889  890              1      1  ...  30.0000   C148         C
890  891              0      3  ...   7.7500    NaN         Q

[891 rows x 12 columns]>

In [ ]:
#Eliminar datos vacíos
df

ID  sobreviviente  Clase  ...   Tarifa Cabina  Embarque
0      1              0      3  ...   7.2500    NaN         S
1      2              1      1  ...  71.2833    C85         C
2      3              1      3  ...   7.9250    NaN         S
3      4              1      1  ...  53.1000   C123         S
4      5              0      3  ...   8.0500    NaN         S
..   ...            ...    ...  ...      ...    ...       ...
886  887              0      2  ...  13.0000    NaN         S
887  888              1      1  ...  30.0000    B42         S
888  889              0      3  ...  23.4500    NaN         S
889  890              1      1  ...  30.0000   C148         C
890  891              0      3  ...   7.7500    NaN         Q

[891 rows x 12 columns]

In [ ]:
#Eliminar filas con datos nulos
df.dropna(axis=0)

ID  sobreviviente  Clase  ...   Tarifa       Cabina  Embarque
1      2              1      1  ...  71.2833          C85         C
3      4              1      1  ...  53.1000         C123         S
6      7              0      1  ...  51.8625          E46         S
10    11              1      3  ...  16.7000           G6         S
11    12              1      1  ...  26.5500         C103         S
..   ...            ...    ...  ...      ...          ...       ...
871  872              1      1  ...  52.5542          D35         S
872  873              0      1  ...   5.0000  B51 B53 B55         S
879  880              1      1  ...  83.1583          C50         C
887  888              1      1  ...  30.0000          B42         S
889  890              1      1  ...  30.0000         C148         C

[183 rows x 12 columns]

In [ ]:
df.dropna(subset=['Cabina'],axis=0)
#df.dropna(subset=['Cabina'],axis=0, inpace=True)

ID  sobreviviente  Clase  ...   Tarifa       Cabina  Embarque
1      2              1      1  ...  71.2833          C85         C
3      4              1      1  ...  53.1000         C123         S
6      7              0      1  ...  51.8625          E46         S
10    11              1      3  ...  16.7000           G6         S
11    12              1      1  ...  26.5500         C103         S
..   ...            ...    ...  ...      ...          ...       ...
871  872              1      1  ...  52.5542          D35         S
872  873              0      1  ...   5.0000  B51 B53 B55         S
879  880              1      1  ...  83.1583          C50         C
887  888              1      1  ...  30.0000          B42         S
889  890              1      1  ...  30.0000         C148         C

[204 rows x 12 columns]

In [ ]:
#Eliminar columnas con datos nulos. Cuáles se eliminaron?
df.dropna(axis=1)

ID  sobreviviente  Clase  ... Hijos            Ticket   Tarifa
0      1              0      3  ...     0         A/5 21171   7.2500
1      2              1      1  ...     0          PC 17599  71.2833
2      3              1      3  ...     0  STON/O2. 3101282   7.9250
3      4              1      1  ...     0            113803  53.1000
4      5              0      3  ...     0            373450   8.0500
..   ...            ...    ...  ...   ...               ...      ...
886  887              0      2  ...     0            211536  13.0000
887  888              1      1  ...     0            112053  30.0000
888  889              0      3  ...     2        W./C. 6607  23.4500
889  890              1      1  ...     0            111369  30.0000
890  891              0      3  ...     0            370376   7.7500

[891 rows x 9 columns]

In [ ]:
#Reemplazar datos faltantes
promedio=df["edad"].mean()
promedio

29.69911764705882

In [ ]:
promedio=30
df["edad"].replace(np.nan,promedio)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    30.0
889    26.0
890    32.0
Name: edad, Length: 891, dtype: float64

In [ ]:
#Cambiar variables categóricas a numéricas
pd.get_dummies(df, columns=['Sexo'])

ID  sobreviviente  Clase  ... Embarque  Sexo_female  Sexo_male
0      1              0      3  ...        S            0          1
1      2              1      1  ...        C            1          0
2      3              1      3  ...        S            1          0
3      4              1      1  ...        S            1          0
4      5              0      3  ...        S            0          1
..   ...            ...    ...  ...      ...          ...        ...
886  887              0      2  ...        S            0          1
887  888              1      1  ...        S            1          0
888  889              0      3  ...        S            1          0
889  890              1      1  ...        C            0          1
890  891              0      3  ...        Q            0          1

[891 rows x 13 columns]

In [ ]:
#A veces tener ya dos variables no es necesario, o al usar un modelo matemático puede generar un error, entonces nos podemos quedar con una sola variable.
#Nos podemos quedar con una sola columna, pero se puede con el mismo comando usando drop_first
pd.get_dummies(df, columns=['Sexo'], drop_first=True)

ID  sobreviviente  Clase  ... Cabina  Embarque  Sexo_male
0      1              0      3  ...    NaN         S          1
1      2              1      1  ...    C85         C          0
2      3              1      3  ...    NaN         S          0
3      4              1      1  ...   C123         S          0
4      5              0      3  ...    NaN         S          1
..   ...            ...    ...  ...    ...       ...        ...
886  887              0      2  ...    NaN         S          1
887  888              1      1  ...    B42         S          0
888  889              0      3  ...    NaN         S          0
889  890              1      1  ...   C148         C          1
890  891              0      3  ...    NaN         Q          1

[891 rows x 12 columns]

In [ ]:
#Agrupamiento de datos. Crear rango etario en vez de la edad.
#bins: Se coloca donde inicia el primer rando y donde terminan todos los rangos:
bins = [0, 5, 12, 18, 35, 60, 100]

In [ ]:
names = ["1", "2", "3", "4", "5", "6"]

In [ ]:
#Metodo cut
df['edad'] = pd.cut(df['edad'], bins, labels = names)

In [ ]:
df

ID  sobreviviente  Clase  ...   Tarifa Cabina Embarque
0      1              0      3  ...   7.2500    NaN        S
1      2              1      1  ...  71.2833    C85        C
2      3              1      3  ...   7.9250    NaN        S
3      4              1      1  ...  53.1000   C123        S
4      5              0      3  ...   8.0500    NaN        S
..   ...            ...    ...  ...      ...    ...      ...
886  887              0      2  ...  13.0000    NaN        S
887  888              1      1  ...  30.0000    B42        S
888  889              0      3  ...  23.4500    NaN        S
889  890              1      1  ...  30.0000   C148        C
890  891              0      3  ...   7.7500    NaN        Q

[891 rows x 12 columns]